In [1]:
import torch

# Define a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Transpose the tensor
transposed_tensor = torch.transpose(tensor, 0, 1)

print("Original tensor:")
print(tensor)
print("Transposed tensor:")
print(transposed_tensor)


Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Transposed tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [2]:
import torch

# Define a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Transpose the tensor
transposed_tensor = tensor.transpose(0, 1)

print("Original tensor:")
print(tensor)
print("Transposed tensor:")
print(transposed_tensor)

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Transposed tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [4]:
q = torch.tensor([1,2,3],dtype=torch.float32)
k = torch.tensor([1,2,3],dtype=torch.float32)

attention_value = torch.softmax(q.dot(k.transpose(0,1))/torch.sqrt(self.hidden_dim))

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [7]:
import torch

# Define tensors
q = torch.tensor([1, 2, 3], dtype=torch.float32).unsqueeze(0)  # Make q 2-dimensional
k = torch.tensor([1, 2, 3], dtype=torch.float32).unsqueeze(0)  # Make k 2-dimensional

print(q)
print(k)

# Transpose k
k_transposed = k.transpose(0, 1)

print(k_transposed)

# Calculate attention value
attention_value = torch.softmax(q.mm(k_transposed) / torch.sqrt(torch.tensor(q.shape[1], dtype=torch.float32)), dim=1)

print("Attention value:", attention_value)


tensor([[1., 2., 3.]])
tensor([[1., 2., 3.]])
tensor([[1.],
        [2.],
        [3.]])
Attention value: tensor([[1.]])


In [1]:
from fastai.text.all import *

ModuleNotFoundError: No module named 'fastai'